#all time/duration based options are in seconds
common: &common
  authentication_user: TGFaYURh
  authentication_pwd: MTJSb2NrVSQ=
  cookies:
    guest: MmYzZDVmMGMtZDgxZC00ODBiLWQzY2YtMGJjMTc0OTdiNjNi
  account_name: TEST
  registered_email: pdp_qaa_3@lzdtest.net
  password_registered_email: cWFjdWN1bWJlcjE=
  price_regex: (?-mix:[0-9\.\,]+)
  checkout_steps_indexes:
    checkout_delivery_information: '1'
    checkout_order_summary: '3'
  user_agent_string:
    operamini: 'Opera/9.80 (J2ME/MIDP; Opera Mini/9.80 (J2ME/23.377; U; en) Presto/2.5.25 Version/10.54'
  review_rejection_reason: 'spam'
  my_review:
    account_email: pdp_qaa_mr_2@lzdtest.net
page_url:
  normal: https://www.lazada.sg/logitech-mk235-keyboard-and-mice-combo-39644681.html?pdpVersion=v2
  digital: https://www.lazada.sg/google-play-gift-code-sgd-30-51661524.html?pdpVersion=v2
  multisource:    https://www.lazada.sg/samsung-galaxy-a7-a7000-4g-lte-smart-phone-dual-sim-black-export-424495.html?pdpVersion=v2
  oos:    https://www.lazada.sg/waterproof-sports-action-camera-dv-dvr-20x9d-sj4000-rose-9511662.html?pdpVersion=v2
  grouping:    https://www.lazada.sg/xianglong-test-pls-dont-buy-lots-of-sku-97287329.html?pdpVersion=v2
  service:    https://www.lazada.sg/longs-test-service-product-pls-dont-buy-166912032.html?pdpVersion=v2
  tbc: https://www.lazada.sg/living-room-entrance-meter-box-decorative-painting-61767783.html?pdpVersion=v2
  voucher:    https://www.lazada.sg/anello-x-legato-largo-original-japan-3-way-tote-bag-should-bag-crossbody-baglarge-size-8006854.html?pdpVersion=v2
  seller_promotion:    https://www.lazada.sg/anello-x-legato-largo-original-japan-3-way-tote-bag-should-bag-crossbody-baglarge-size-8006854.html?pdpVersion=v2
  shipped_from_overseas:    https://www.lazada.sg/voyager-test-product-test-cb-product-with-fbl-stock-94140529.html?pdpVersion=v2
  many_pictures:   https://www.lazada.sg/wd06-c-mobile-phone-charging-base-mobile-phone-charging-bracket-three-bracket-with-bamboo-wood-charging-function-intl-61802881.html?pdpVersion=v2
  official_store: https://www.lazada.sg/jabra-elite-sport-upgraded-70051257.html?pdpVersion=v2
  video: https://www.lazada.sg/jabra-elite-sport-upgraded-70051257.html?pdpVersion=v2